server:
  port: 0

spring:
  application:
    name: auto-hub-reactive-invoice-notification
  mongodb:
    database: auto_hub_invoice_notification
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@autohubinvoicenotificat.ciwvits.mongodb.net/?appName=AutoHubInvoiceNotification
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    function:
      definition: customerInfoConsumer;invoiceNotificationConsumer
    stream:
      defaultBinder: kafka
      bindings:
        customerInfoConsumer-in-0:
          binder: kafka
          destination: ${CUSTOMER_INFO_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EMAIL_NOTIFICATION_CONSUMER_GROUP}
        invoiceNotificationConsumer-in-0:
          binder: kafka
          destination: ${EMAIL_NOTIFICATION_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EMAIL_NOTIFICATION_CONSUMER_GROUP}
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          customerInfoConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          invoiceNotificationConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
  web:
    resources:
      add-mappings: false
    error:
      include-message: always
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false
  http:
    codecs:
      max-in-memory-size: 20MB
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${MAILJET_API_KEY}
    password: ${MAILJET_SECRET_KEY}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    eureka-server-port: 8861
    service-url:
      defaultZone: http://localhost:8861/eureka/
    proxy-password: ${EUREKA_USER}
    proxy-user-name: ${EUREKA_PASSWORD}
  instance:
    prefer-ip-address: true

mail:
  from: ${MAIL_FROM}
  name: Auto Hub

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongodb:
      enabled: false

logging:
  level:
    org:
      springframework:
        security: ERROR
        web: ERROR
