server:
  port: 0

spring:
  application:
    name: auto-hub-reactive-agency
  webflux:
    base-path: /agency
  mongodb:
    database: auto_hub_agency
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@autohubagency.2b57qdk.mongodb.net/?retryWrites=true&w=majority&appName=AutoHubAgency
    representation:
      uuid: standard
  data:
    mongodb:
      representation:
        big-decimal: decimal128
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    function:
      definition: updatedCarBookingSavedConsumer;updatedCarBookingUpdatedConsumer;updatedCarInvoiceClosedConsumer
    stream:
      defaultBinder: kafka
      bindings:
        updatedCarBookingSavedConsumer-in-0:
          binder: kafka
          destination: ${SAVE_BOOKING_CAR_UPDATE_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AGENCY_CONSUMER_GROUP}
        updatedCarBookingUpdatedConsumer-in-0:
          binder: kafka
          destination: ${UPDATE_BOOKING_CARS_UPDATE_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AGENCY_CONSUMER_GROUP}
        updatedCarInvoiceClosedConsumer-in-0:
          binder: kafka
          destination: ${INVOICE_CAR_UPDATE_DETAILS_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AGENCY_CONSUMER_GROUP}
        carAvailableProducer-out-0:
          binder: kafka
          destination: ${CAR_AVAILABLE_AI_REACTIVE_TOPIC}
          contentType: application/json
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          updatedCarBookingSavedConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          updatedCarBookingUpdatedConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          updatedCarInvoiceClosedConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
  web:
    resources:
      add-mappings: false
    error:
      include-message: always
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false
  docker:
    compose:
      enabled: false
  http:
    codecs:
      max-in-memory-size: 20MB

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    eureka-server-port: 8861
    service-url:
      defaultZone: http://localhost:8861/eureka/
    proxy-password: ${EUREKA_USER}
    proxy-user-name: ${EUREKA_PASSWORD}
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongodb:
      enabled: false

logging:
  level:
    org:
      mongodb:
        driver: ERROR
      springframework:
        boot:
          autoconfigure:
            mongo: ERROR
        security: ERROR
        web: ERROR
        data:
          mongodb:
            driver: DEBUG
            core:
              ReactiveMongoTemplate: ERROR

apikey:
  secret: ${API_KEY_SECRET}

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  codecMaxInMemorySizeInMb: 20

migration:
  package-scan: com.autohubreactive.agency.migration
