server:
  port: 0

spring:
  application:
    name: auto-hub-reactive-ai
  webflux:
    base-path: /ai
  mongodb:
    database: auto_hub_ai
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@autohubai.gnfkdzp.mongodb.net/?appName=AutoHubAi
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.0F
          format: json
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      mongodb:
        collection-name: car-vector
        initialize-schema: true
        index-name: car-vector-index
        path-name: embedding
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    function:
      definition: carStatusUpdateConsumer;updateCarsConsumer;carUpdateDetailsConsumer;carAvailableConsumer
    stream:
      defaultBinder: kafka
      bindings:
        carStatusUpdateConsumer-in-0:
          binder: kafka
          destination: ${SAVE_BOOKING_CAR_UPDATE_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
        updateCarsConsumer-in-0:
          binder: kafka
          destination: ${UPDATE_BOOKING_CARS_UPDATE_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
        carUpdateDetailsConsumer-in-0:
          binder: kafka
          destination: ${INVOICE_CAR_UPDATE_DETAILS_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
        carAvailableConsumer-in-0:
          binder: kafka
          destination: ${CAR_AVAILABLE_AI_REACTIVE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          carStatusUpdateConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          updateCarsConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          carUpdateDetailsConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          carAvailableConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      enable-auto-commit: false
  http:
    codecs:
      max-in-memory-size: 20MB
  web:
    error:
      include-message: always
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    eureka-server-port: 8861
    service-url:
      defaultZone: http://localhost:8861/eureka/
    proxy-password: ${EUREKA_USER}
    proxy-user-name: ${EUREKA_PASSWORD}
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs
  show-actuator: true

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongodb:
      enabled: false

logging:
  level:
    org:
      springframework:
        security: ERROR
        web: ERROR

apikey:
  secret: ${API_KEY_SECRET}

webclient:
  url:
    auto-hub-agency-cars: http://auto-hub-reactive-agency/agency/cars

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  codecMaxInMemorySizeInMb: 20

vector-store:
  system-roles: ROLE_admin
